In [1]:
import torch

In [2]:
zeros = torch.zeros([2, 2])
zeros

tensor([[0., 0.],
        [0., 0.]])

In [3]:
zeros[:,-512:]

tensor([[0., 0.],
        [0., 0.]])

In [4]:
t1 = torch.tensor([1, 2])
t1.dim()

1

In [5]:
t1.unsqueeze(1).shape

torch.Size([2, 1])

In [6]:
from pathlib import Path
import re

In [7]:
alllines = Path('../data/shakespeare/alllines.txt')

In [8]:
with open(alllines) as f:
    content = f.read()

In [9]:
lines = content.split("\n")

In [10]:
lines = [re.sub(r'(^"|"$)', '', l) for l in lines]

In [11]:
with open('../data/shakespeare/alllines_clean.txt', 'w') as f:
    f.write("\n".join(lines))

In [12]:
with open('../data/shakespeare/alllines_clean.txt', 'r') as f:
    print(f.read())

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [13]:
!pip install tiktoken

  Using cached tiktoken-0.3.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip


In [14]:
import tiktoken

In [18]:
enc = tiktoken.get_encoding("cl100k_base")

In [19]:
ten_lines = "\n".join(lines[:10])

In [20]:
encoded = enc.encode(ten_lines)

In [39]:
len(set(encoded)), len(encoded), sorted(set(encoded))

(95,
 116,
 [11,
  13,
  43,
  198,
  264,
  279,
  287,
  291,
  304,
  311,
  315,
  323,
  328,
  345,
  358,
  369,
  387,
  392,
  420,
  439,
  449,
  468,
  473,
  502,
  527,
  543,
  578,
  584,
  596,
  627,
  643,
  779,
  810,
  892,
  965,
  1077,
  1271,
  1866,
  2059,
  2512,
  2695,
  2822,
  2871,
  2875,
  2911,
  2967,
  3067,
  3083,
  3112,
  3624,
  3885,
  4208,
  4516,
  4985,
  5151,
  5613,
  6403,
  6680,
  6966,
  7295,
  8839,
  8870,
  9096,
  10086,
  11492,
  15195,
  17003,
  17614,
  20396,
  23726,
  26346,
  30647,
  33763,
  35263,
  37397,
  37420,
  40915,
  44439,
  47525,
  47798,
  49196,
  54352,
  58477,
  59570,
  65362,
  66190,
  66900,
  69864,
  70549,
  74911,
  76275,
  78853,
  91396,
  98208,
  99378])

In [22]:
print(encoded)

[6966, 358, 198, 3624, 37420, 358, 13, 7295, 13, 578, 44439, 627, 6403, 74911, 473, 965, 11492, 11, 58477, 76275, 3083, 47525, 35263, 643, 11, 279, 91396, 43, 315, 66190, 47798, 40915, 11, 328, 2871, 468, 49196, 15195, 70549, 11, 323, 3885, 198, 4516, 66900, 439, 584, 527, 11, 779, 78853, 449, 2512, 345, 10086, 584, 264, 892, 369, 30647, 291, 9096, 311, 26346, 345, 3112, 37397, 2875, 2695, 17003, 59570, 315, 502, 2967, 8839, 198, 1271, 387, 65362, 304, 69864, 99378, 8870, 627, 2822, 810, 279, 98208, 20396, 315, 420, 17614, 198, 2059, 543, 3067, 392, 1077, 23726, 449, 1077, 1866, 2911, 596, 6680, 345, 33763, 810, 4985, 54352, 287, 4208, 5613, 1077, 5151, 11]


In [21]:
print(enc.decode(encoded))

ACT I
SCENE I. London. The palace.
Enter KING HENRY, LORD JOHN OF LANCASTER, the EARL of WESTMORELAND, SIR WALTER BLUNT, and others
So shaken as we are, so wan with care,
Find we a time for frighted peace to pant,
And breathe short-winded accents of new broils
To be commenced in strands afar remote.
No more the thirsty entrance of this soil
Shall daub her lips with her own children's blood,
Nor more shall trenching war channel her fields,


In [44]:
dir(enc)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_core_bpe',
 '_encode_bytes',
 '_encode_only_native_bpe',
 '_encode_single_piece',
 '_mergeable_ranks',
 '_pat_str',
 '_special_tokens',
 'decode',
 'decode_bytes',
 'decode_single_token_bytes',
 'decode_tokens_bytes',
 'encode',
 'encode_batch',
 'encode_ordinary',
 'encode_ordinary_batch',
 'encode_single_token',
 'encode_with_unstable',
 'eot_token',
 'max_token_value',
 'n_vocab',
 'name',
 'special_tokens_set',
 'token_byte_values']

In [45]:
enc.n_vocab

100277

In [29]:
enc.token_byte_values()[:10]

[b'\x00',
 b'\x01',
 b'\x02',
 b'\x03',
 b'\x04',
 b'\x05',
 b'\x06',
 b'\x07',
 b'\x08',
 b'\t']

In [31]:
data = torch.tensor(enc.encode(ten_lines), dtype=torch.long)

In [35]:
n = int(0.8 * len(data))
data[:n]

tensor([ 6966,   358,   198,  3624, 37420,   358,    13,  7295,    13,   578,
        44439,   627,  6403, 74911,   473,   965, 11492,    11, 58477, 76275,
         3083, 47525, 35263,   643,    11,   279, 91396,    43,   315, 66190,
        47798, 40915,    11,   328,  2871,   468, 49196, 15195, 70549,    11,
          323,  3885,   198,  4516, 66900,   439,   584,   527,    11,   779,
        78853,   449,  2512,   345, 10086,   584,   264,   892,   369, 30647,
          291,  9096,   311, 26346,   345,  3112, 37397,  2875,  2695, 17003,
        59570,   315,   502,  2967,  8839,   198,  1271,   387, 65362,   304,
        69864, 99378,  8870,   627,  2822,   810,   279, 98208, 20396,   315,
          420, 17614])